#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Meshing
runApplication blockMesh > bm.log
runApplication topoSet > ts.log
runApplication splitMeshRegions -cellZones -overwrite > smr.log

# Post-process
#paraFoam -touchAll

#------------------------------------------------------------------------------
